version: '3.3'

services:
    web:
        build: .
        container_name: dashboard-app
        ports:
            - "8501:8501"
        depends_on:
            - db
        volumes:
            - .:/app
    db:
        image: mysql:5.7
        container_name: dashboarding-db
        environment:
              MYSQL_ROOT_PASSWORD: test
              MYSQL_DATABASE: investimentos
              MYSQL_USER: test
              MYSQL_PASSWORD: test
        ports:
            - "3306:3306"
        expose:
            - '3306'
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
