version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: investimentos
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    expose:
        - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
